"""init models

Revision ID: 35dc13600de8
Revises: c708d80f0cb4
Create Date: 2025-08-25 11:59:40.786728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35dc13600de8'
down_revision: Union[str, Sequence[str], None] = 'c708d80f0cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directions', type_='foreignkey')
    op.create_foreign_key(None, 'directions', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'kafedras', type_='foreignkey')
    op.create_foreign_key(None, 'kafedras', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'literature', type_='foreignkey')
    op.create_foreign_key(None, 'literature', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subject_directions', type_='foreignkey')
    op.drop_constraint(None, 'subject_directions', type_='foreignkey')
    op.create_foreign_key(None, 'subject_directions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subject_directions', 'directions', ['direction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subjects', 'kafedras', ['kafedra_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'kafedras', ['kafedra_id'], ['id'])
    op.create_foreign_key(None, 'subjects', 'universities', ['university_id'], ['id'])
    op.drop_constraint(None, 'subject_directions', type_='foreignkey')
    op.drop_constraint(None, 'subject_directions', type_='foreignkey')
    op.create_foreign_key(None, 'subject_directions', 'directions', ['direction_id'], ['id'])
    op.create_foreign_key(None, 'subject_directions', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'literature', type_='foreignkey')
    op.create_foreign_key(None, 'literature', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'kafedras', type_='foreignkey')
    op.create_foreign_key(None, 'kafedras', 'universities', ['university_id'], ['id'])
    op.drop_constraint(None, 'directions', type_='foreignkey')
    op.create_foreign_key(None, 'directions', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###
