"""update models

Revision ID: 536114a378b6
Revises: 55dc0df43327
Create Date: 2025-11-20 07:10:10.221802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '536114a378b6'
down_revision: Union[str, Sequence[str], None] = '55dc0df43327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_direction_unique', 'directions', ['number', 'name', 'course', 'university_id'])
    op.alter_column('literature', 'language',
               existing_type=postgresql.ENUM('uzbek', 'russian', 'karakalpak', 'english', name='languageenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('literature', 'font_type',
               existing_type=postgresql.ENUM('kirill', 'latin', 'english', name='fonttypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('literature', 'condition',
               existing_type=postgresql.ENUM('actual', 'unactual', name='conditionenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('literature', 'usage_status',
               existing_type=postgresql.ENUM('use', 'unused', name='usagestatusenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('literature', 'usage_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('use', 'unused', name='usagestatusenum'),
               existing_nullable=False)
    op.alter_column('literature', 'condition',
               existing_type=sa.String(),
               type_=postgresql.ENUM('actual', 'unactual', name='conditionenum'),
               existing_nullable=False)
    op.alter_column('literature', 'font_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('kirill', 'latin', 'english', name='fonttypeenum'),
               existing_nullable=False)
    op.alter_column('literature', 'language',
               existing_type=sa.String(),
               type_=postgresql.ENUM('uzbek', 'russian', 'karakalpak', 'english', name='languageenum'),
               existing_nullable=False)
    op.drop_constraint('uq_direction_unique', 'directions', type_='unique')
    # ### end Alembic commands ###
