"""add file_path2

Revision ID: 7860bc8c5f87
Revises: f7861f54c1e4
Create Date: 2026-01-30 09:49:04.983594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7860bc8c5f87'
down_revision: Union[str, Sequence[str], None] = 'f7861f54c1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literature', sa.Column('file_path_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('literature', 'file_path_2')
    # ### end Alembic commands ###
