"""student_count nullable

Revision ID: f7861f54c1e4
Revises: 71ecce61289d
Create Date: 2025-11-21 16:22:49.559043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7861f54c1e4'
down_revision: Union[str, Sequence[str], None] = '71ecce61289d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directions', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directions', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
