from .user import User
from .admin import Admin
from .university import University
from .direction import Direction
from .kafedra import Kafedra
from .subject import Subject
from .literature import Literature
from .news import News
from .tag import Tag
